### PR TITLE
Cargo.toml now has cargo-generate, and .pngs for main boards resize to omit extra space

### PR DESCRIPTION
**Pull request by jetfuel268**

### CODE REVIEW

**Comment by shulltronics** [comment]
Hey @perezandy -- will you separate out the wasm-annotations from this PR? I want to pull in the initial changes (finally!), but would like to keep the WASM stuff as an open PR (it's very useful - thank you).

**Comment by perezandy** [comment]
Done! I saved the annotations to a separate branch

**Comment by shulltronics** [comment]
Looks great! Last thing, can you pull in the recent changes from my main branch? There are some small fixes I've made since the PR was opened.

**Comment by perezandy** [comment]
Done again!

**Pull request merged**
